name: aienv_dev
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiofiles=23.1.0=pyhd8ed1ab_1
  - aiohttp=3.8.3=py310h5eee18b_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - altair=5.0.1=pyhd8ed1ab_1
  - anyio=3.7.1=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - bcrypt=3.2.2=py310h5764c6d_1
  - beautifulsoup4=4.11.1=py310h06a4308_0
  - binutils_impl_linux-64=2.40=hf600244_0
  - blas=1.1=openblas
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli-python=1.0.9=py310hd8f1fbe_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py310h74dc2b5_0
  - chardet=5.2.0=py310hff52083_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.4=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=38.0.4=py310h597c629_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses-json=0.5.7=pyhd8ed1ab_0
  - distro=1.8.0=pyhd8ed1ab_0
  - docker-compose=1.29.2=py310hff52083_1
  - docker-py=6.1.3=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - dockerpty=0.4.1=py_0
  - docopt=0.6.2=py_1
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - exceptiongroup=1.1.2=pyhd8ed1ab_0
  - ffmpeg=4.2.2=h20bf706_0
  - ffmpy=0.3.0=pyhb6f538c_0
  - filelock=3.12.2=pyhd8ed1ab_0
  - flask=2.2.2=py310h06a4308_0
  - freetype=2.10.4=h0708190_1
  - frozenlist=1.3.3=py310h5eee18b_0
  - fsspec=2023.6.0=pyh1a96a4e_0
  - gcc=13.1.0=h8e92de4_1
  - gcc_impl_linux-64=13.1.0=hc4be1a9_0
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.32=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gradio=3.23.0=pyhd8ed1ab_0
  - greenlet=2.0.1=py310h6a678d5_0
  - gxx=13.1.0=h8e92de4_1
  - gxx_impl_linux-64=13.1.0=hc4be1a9_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=0.17.3=pyhd8ed1ab_0
  - httpx=0.24.1=pyhd8ed1ab_0
  - huggingface_hub=0.16.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=58.2=he6710b0_3
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_resources=6.0.0=pyhd8ed1ab_1
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.0=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_1
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - kernel-headers_linux-64=2.6.32=he073ed8_16
  - kiwisolver=1.4.4=py310h6a678d5_0
  - lame=3.100=h7f98852_1001
  - langchain=0.0.190=pyhd8ed1ab_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=15_linux64_openblas
  - libcblas=3.9.0=15_linux64_openblas
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.3=he6710b0_2
  - libgcc-devel_linux-64=13.1.0=he3cc6c4_0
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libgomp=13.1.0=he5830b7_0
  - liblapack=3.9.0=15_linux64_openblas
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsanitizer=13.1.0=hfd8a6a1_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-devel_linux-64=13.1.0=he3cc6c4_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.5.0=h6a678d5_2
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - linkify-it-py=2.0.0=pyhd8ed1ab_0
  - lxml=4.9.1=py310h1edc446_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - marshmallow=3.19.0=pyhd8ed1ab_0
  - marshmallow-enum=1.5.1=pyh9f0ad1d_3
  - matplotlib-base=3.4.3=py310h23f4a51_2
  - mdit-py-plugins=0.3.3=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - multidict=6.0.2=py310h5eee18b_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - numexpr=2.8.4=py310h757a811_1
  - numpy=1.22.3=py310h4ef5377_2
  - openai=0.27.8=pyhd8ed1ab_0
  - openapi-schema-pydantic=1.2.4=pyhd8ed1ab_0
  - openblas=0.3.20=pthreads_h320a7e8_0
  - openh264=2.1.1=h4ff587b_0
  - openpyxl=3.0.9=pyhd8ed1ab_0
  - openssl=1.1.1v=hd590300_0
  - orjson=3.8.8=py310h52d8a92_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=1.5.3=py310h1128e8f_0
  - pandas-stubs=1.2.0.62=py310hff52083_0
  - paramiko=3.3.1=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.1.2=py310h06a4308_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - plotly=5.15.0=pyhd8ed1ab_0
  - pluggy=1.0.0=py310h06a4308_1
  - protobuf=3.20.3=py310h6a678d5_0
  - psutil=5.9.0=py310h5eee18b_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.8=py310h5eee18b_0
  - pydub=0.25.1=pyhd8ed1ab_0
  - pynacl=1.5.0=py310h5764c6d_2
  - pyparsing=3.1.0=pyhd8ed1ab_0
  - pyrsistent=0.18.0=py310h7f8727e_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.3.1=py310h06a4308_0
  - python=3.10.0=h12debd9_5
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-dotenv=1.0.0=pyhd8ed1ab_0
  - python-multipart=0.0.6=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2023.3=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0=py310h5764c6d_4
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py310h1246948_0
  - scipy=1.8.1=py310h7612f91_0
  - semantic_version=2.10.0=pyhd8ed1ab_0
  - sentry-sdk=1.28.0=pyhd8ed1ab_0
  - setproctitle=1.2.2=py310h5764c6d_2
  - setuptools=67.8.0=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=py310h06a4308_0
  - sqlalchemy=1.4.39=py310h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - starlette=0.27.0=pyhd8ed1ab_0
  - stringcase=1.2.0=py_0
  - sysroot_linux-64=2.12=he073ed8_16
  - tenacity=8.2.2=pyhd8ed1ab_0
  - texttable=1.6.7=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py310h06a4308_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.1=py310h5764c6d_3
  - tqdm=4.65.0=pyhd8ed1ab_1
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - typing_inspect=0.9.0=pyhd8ed1ab_0
  - tzdata=2023c=h04d1e81_0
  - uc-micro-py=1.0.1=pyhd8ed1ab_0
  - urllib3=2.0.3=pyhd8ed1ab_1
  - uvicorn=0.22.0=py310hff52083_0
  - wandb=0.15.5=pyhd8ed1ab_0
  - websocket-client=1.6.1=pyhd8ed1ab_0
  - websockets=10.4=py310h5eee18b_1
  - werkzeug=2.2.2=py310h06a4308_0
  - wheel=0.38.4=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py310h5764c6d_2
  - zipp=3.16.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - accelerate==0.21.0
      - backoff==2.2.1
      - bitsandbytes==0.41.1
      - chroma-hnswlib==0.7.2
      - chromadb==0.4.6
      - clickhouse-connect==0.6.6
      - cmake==3.25.0
      - coloredlogs==15.0.1
      - duckdb==0.8.1
      - fastapi==0.99.1
      - flatbuffers==23.5.26
      - hnswlib==0.7.0
      - httptools==0.6.0
      - humanfriendly==10.0
      - lit==15.0.7
      - lz4==4.3.2
      - monotonic==1.6
      - mpmath==1.3.0
      - networkx==3.0
      - nltk==3.8.1
      - onnxruntime==1.15.1
      - overrides==7.3.1
      - peft==0.4.0
      - podman-compose==1.0.6
      - posthog==3.0.1
      - pulsar-client==3.2.0
      - pypdf==3.14.0
      - pypika==0.48.9
      - python-redmine==2.4.0
      - regex==2023.6.3
      - safetensors==0.3.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - sympy==1.12
      - tiktoken==0.4.0
      - tokenizers==0.13.3
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118
      - transformers==4.31.0
      - triton==2.0.0
      - uvloop==0.17.0
      - watchfiles==0.19.0
      - zstandard==0.21.0
prefix: /work/submit/juliush/.conda/envs/aienv_dev
