[project]
name = "a2rchi"
version = "1.1.0"
description = "An AI Augmented Research Chat Intelligence (A2rchi)"
requires-python = ">=3.7"
authors = [
    {name="Pietro Lugato", email="pmlugato@mit.edu"},
    {name="Julius Heitkoetter", email="juliush@mit.edu"},
    {name="Tim Kraska", email="kraska@mit.edu"},
    {name="Christoph Paus", email="paus@mit.edu"},
    {name="Matthew Russo", email="mdrusso@mit.edu"}
]
dependencies = [
    "pyyaml==6.0.1",
    "click==8.1.7",
    "jinja2==3.1.3",
    "requests==2.31.0",
    "podman-compose==1.4.0",
    "mkdocs"
]

[project.scripts]
a2rchi = "a2rchi.cli.cli_main:main"

[tool.setuptools.package-data]
a2rchi = ["templates/*", "templates/grafana/*"]

[tool.setuptools]
packages = [
    "a2rchi",
    "a2rchi.bin",
    "a2rchi.cli",
    "a2rchi.chains",
    "a2rchi.chains.utils",
    "a2rchi.interfaces",
    "a2rchi.interfaces.chat_app",
    "a2rchi.interfaces.uploader_app",
    "a2rchi.interfaces.grader_app",
    "a2rchi.templates",
    "a2rchi.templates.grafana",
    "a2rchi.utils",
]

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/mit-submit/A2rchi"
