[project]
name = "a2rchi"
version = "1.1.0"
description = "An AI Augmented Research Chat Intelligence (A2rchi)"
requires-python = ">=3.7"
authors = [
    {name="Pietro Lugato", email="pmlugato@mit.edu"},
    {name="Julius Heitkoetter", email="juliush@mit.edu"},
    {name="Tim Kraska", email="kraska@mit.edu"},
    {name="Christoph Paus", email="paus@mit.edu"},
    {name="Matthew Russo", email="mdrusso@mit.edu"}
]
dependencies = [
    "pyyaml==6.0.1",
    "click==8.1.7",
    "jinja2==3.1.3",
    "requests==2.31.0",
    "podman-compose==1.4.0",
    "python-dotenv>=0.19.0",
    "mkdocs"
]

[project.scripts]
a2rchi = "src.cli.cli_main:main"

[tool.setuptools.package-data]
a2rchi = ["cli/templates/*", "cli/templates/grafana/*"]

[tool.setuptools]
packages = [
    "src",
    "src.a2rchi",
    "src.a2rchi.utils",
    "src.bin",
    "src.cli",
    "src.cli.utils",
    "src.cli.managers",
    "src.cli.templates",
    "src.cli.templates.grafana",
    "src.data_manager",
    "src.data_manager.collectors",
    "src.data_manager.collectors.scrapers",
    "src.data_manager.collectors.scrapers.integrations",
    "src.data_manager.collectors.tickets",
    "src.data_manager.collectors.tickets.integrations",
    "src.data_manager.collectors.utils",
    "src.interfaces",
    "src.interfaces.chat_app",
    "src.interfaces.uploader_app",
    "src.interfaces.grader_app",
    "src.interfaces.redmine_mailer_integration",
    "src.interfaces.redmine_mailer_integration.utils",
    "src.utils",
]

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/mit-submit/A2rchi"
