apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: postgres:5432  # templated by install script
    user: grafana
    secureJsonData:
      password: {{ grafana_pg_password }}
    jsonData:
      database: a2rchi-db
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1000 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10; 1000 refers to >= v10
      timescaledb: false
