name: OpenAIEmbedding

global:
  TRAINED_ON: "the SubMIT Cluster"  

data_manager:
  input_lists:  
    - configs/ppc.list
  chromadb_port: 8000
  chromadb_external_port: 8001
  embedding_name: OpenAIEmbeddings

a2rchi:
  pipelines: 
   - QAPipeline
  pipeline_map:
    QAPipeline:
      prompts:
        required:
          condense_prompt: configs/prompts/condense.prompt  
          chat_prompt: configs/prompts/submit.prompt  
      models:
        required:
          chat_model: OpenAIGPT4
          condense_model: OpenAIGPT4


services:
  benchmarking: 
    queries_path: "queries.json"
    out_dir: "bench_out"
    modes: 
      - "RAGAS"
      - "LINKS"

