name: Deploy A2rchi
run-name: ${{ github.actor }} deploys A2rchi
on: [push]
jobs:
  deploy-dev-system:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: |
          ls ~
          ls ~/.ssh/
          cat ~/.ssh/config
      # - run: |
      #     touch ~/.ssh/id_rsa_submit
      #     echo ${{ secrets.SSH_PRIVATE_KEY_MDRUSSO }} >> ~/.ssh/id_rsa_submit

      # - uses: webfactory/ssh-agent@v0.8.0
      #   with:
      #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_MDRUSSO }}
      # - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."

