name: Deploy A2rchi
run-name: ${{ github.actor }} deploys A2rchi
on: [push]
jobs:
  deploy-dev-system:
    runs-on: ubuntu-latest
    steps:
      - env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: |
          mkdir -p /home/runner/.ssh/
          touch /home/runner/.ssh/config
          echo "${{ secrets.SSH_PRIVATE_KEY_MDRUSSO }}" >> /home/runner/.ssh/id_rsa_submit
          chmod 600 /home/runner/.ssh/id_rsa_submit
          cp ${{ github.workspace}}/deploy/ssh_config /home/runner/.ssh/config
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/id_rsa_submit
          ssh submit 'bash -s' < ${{ github.workspace }}/deploy/install.sh

      # - uses: webfactory/ssh-agent@v0.8.0
      #   with:
      #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_MDRUSSO }}
      # - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."

